# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-json
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.6
  hooks:
  - id: clang-format
- repo: https://github.com/PyCQA/pylint
  rev: v3.0.0b0
  hooks:
  - id: pylint
    additional_dependencies: ["psutil"]
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v2.0.4
  hooks:
  - id: autopep8
    additional_dependencies:
    - psutil
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell
