env:
  global:
    - secure: "NlWO/NTPlOU6cowOMuPOvjAprXVwIjmpHHf9CoMR71E2c/eBFFKIHj10kXuyFwz2KihHAIExmo9OlGtGniNWobvIrVrabO3dsOSb6UGbPAQkzQiyQLKsDNQAZx3nMuWEKBtMsVRee6rd7/2uGTY4WB5Ot3VhrUYcN1FoRgQQ9gk="

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.5
      env:
        - QT_SELECT=qt5

language: cpp
compiler:
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - qmake ..
  - make
  - make check

notifications:
  email:
    recipients:
    - allen.winter@kdab.com
    on_success:  never
    on_failure: always

dist: bionic
addons:
  apt:
    update: true
    packages:
    - qt5-default
    - qtbase5-dev
    - qtbase5-dev-tools
    - qtbase5-private-dev
    - qttools5-dev
    - qttools5-dev-tools
  homebrew:
    update: true
    packages:
    - qt5
